%% MSPR recap 04/01/2016

%% GENERAL QUESTIONS

% Q: describe what a classification task is
% A: classification is a way to determine which could be the best
% measurement in order to predict whether a subject belongs to a
% distribution or to another one, based on previous knowledge from a known
% dataset


% Q: explain discriminant analysis as Bayesian classification
% A: Bayesian classification tells us if a new test subject belongs to one
% class or to another based on his probability to be generated by a normal
% distribution. If probability is larger for first class, then the subject 
% is well described from that class.

% a. make an histogram
% b. fit a gaussian to the histogram
% (required parameters: sample mean and variance for each class)
% mean: center of gaussian bell
% variance: how much the bell is spread or squeezed


% Q: what is correlation?
% A: correlation is a scaled covariance matrix divided by standard
% deviations of the taken features. Values range from -1 (negatively
% correlated) to 1 (positively correlated) with 0 being the maximum
% non-correlation.


% Q: what is overfitting?
% A: 


% Q: explain the difference between parametric and non-parametric density
% estimation
% A:


% Q: what is the difference between classification and regression?
% A: classification predicts onlt categorical or discrete variables, while
% regression is able to predict continuous variables.


%% SLIDE PRESENTATION

% It should take not more than 5 minutes
% NO CODE
% show results and plot most significant graphics
% (choose test data randomly and perform cross-validation on 70%)