function name = weekday(d, m, y)

month_codes = [6,2,2,5,0,3,5,1,4,6,2,4];
C = month_codes(m);
names = {...
    'Sun',...
    'Mon',...
    'Tue',...
    'Wed',...
    'Thu',...
    'Fri',...
    'Sat',...
    };

w = mod((d+C+y+floor(y/4)), 7);
name = names{w+1}; % indices in range 0:6 but Matlab starts from 1

end
